// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Models;

#nullable disable

namespace WebApp.Migrations
{
    [DbContext(typeof(AppDbContex))]
    [Migration("20241106183824_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("WebApp.Models.KomputerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataProdukcji")
                        .HasColumnType("TEXT")
                        .HasColumnName("data produkcji");

                    b.Property<string>("KartaGraficzna")
                        .HasColumnType("TEXT")
                        .HasColumnName("karta graficzna");

                    b.Property<string>("Nazwa")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Pamiec")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Procesor")
                        .HasColumnType("TEXT");

                    b.Property<string>("Producent")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("computers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 4,
                            Created = new DateTime(2024, 11, 6, 19, 38, 24, 309, DateTimeKind.Local).AddTicks(6078),
                            DataProdukcji = new DateTime(2000, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KartaGraficzna = "NVIDIA",
                            Nazwa = "Gaming Machine Pro",
                            Pamiec = 16,
                            Procesor = "Intel i5",
                            Producent = "Mateusz Matysiak"
                        },
                        new
                        {
                            Id = 2,
                            Category = 1,
                            Created = new DateTime(2024, 11, 6, 19, 38, 24, 309, DateTimeKind.Local).AddTicks(6136),
                            DataProdukcji = new DateTime(1997, 12, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            KartaGraficzna = "NVIDIA",
                            Nazwa = "Quiet-book",
                            Pamiec = 16,
                            Procesor = "Intel i7",
                            Producent = "Karolina Bruzda"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
